global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: controller-simulator
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [controller-simulator:8081]

  - job_name: edge-collector
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [edge-collector:8082]

  - job_name: telemetry-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [telemetry-gateway:8080]

  - job_name: telemetry-worker
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [telemetry-worker:8083]

  - job_name: rabbitmq
    static_configs:
      - targets: [rabbitmq:15692]

  - job_name: rabbitmq-per-object
    metrics_path: /metrics/per-object
    static_configs:
      - targets: [rabbitmq:15692]
