package dev.telemetrylab.contracts;

public enum ReasonCode {
  MISSING_SOURCE_TAG,
  UNKNOWN_SOURCE_TAG,
  UNSUPPORTED_RAW_UNIT,
  NON_NUMERIC_VALUE,
  NON_FINITE_VALUE,
  VALUE_OUT_OF_RANGE,
  TIMESTAMP_TOO_FAR_IN_FUTURE,
  OUT_OF_ORDER,
  LATE_ARRIVAL,
  BAD_SOURCE_QUALITY,
  DUPLICATE_OBSERVATION,
  IDENTITY_CONFLICT,
  CHECKSUM_MISMATCH,
  UNSUPPORTED_CONTRACT_VERSION,
  INVALID_ENVELOPE,
  TOO_MANY_OBSERVATIONS,
  FIELD_TOO_LONG
}
